### ISSUE TITLE
environment setup questions

### ISSUE THREAD

**Issue by ehwest** [monolithh/aws_fargate_boto3#1]
1) need some guidance on the
Required Setup in advance:
$pip install boto3

2)  How to fix?  
....
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the CreateUser operation: User: arn:aws:iam::195989587001:user/ecs_test_user is not authorized to perform: iam:CreateUser on resource: arn:aws:iam::195989587001:user/fargate-user-1544028719

**Comment by monolithh** [comment]
@ehwest 
1) i update README and added requirements.txt
2) make sure that you have permission for `CreateUser`

**Comment by ehwest** [comment]
Can you provide the instructions or script to CreateUser with the smallest permissions possible, but sufficient to do this task in a specific region?

**Comment by monolithh** [comment]
@ehwest my solution (this solution) before create infrastructure create user (child user) with minimal needed permission. but for create this child user (with minimal permissions) you need to specify parent user which have permission in AWS `CreateUser` for creating child user

see README. 1st step
