### ISSUE TITLE
Error trying to run the create_infrastructure.py script

### ISSUE THREAD

**Issue by mairadanielaferrari** [monolithh/aws_fargate_boto3#2]
I receive the following error while trying to run the create_infrastructer.py script using credentails obtained from the create_user.py

I got an error while running the create-infrastructure script
Create service
Traceback (most recent call last):
 File "create_infrastructure.py", line 449, in <module>
   serviceARN = create_fargate_service(tgARN, subnets, containerSGID)
 File "create_infrastructure.py", line 396, in create_fargate_service
   schedulingStrategy='REPLICA',  # 'REPLICA'|'DAEMON'
 File "/usr/lib/python3.4/site-packages/botocore/client.py", line 320, in _api_call
   return self._make_api_call(operation_name, kwargs)
 File "/usr/lib/python3.4/site-packages/botocore/client.py", line 624, in _make_api_call
   raise error_class(parsed_response, operation_name)
botocore.errorfactory.InvalidParameterException: An error occurred (InvalidParameterException) when calling the CreateService operation: Unable to assume the servicelinked role. Please verify that the ECS service linked role exists.

Command that I am executing is. 

python3 create_infrastructure.py --region us-east-2 --access-key AAAA --secret-key BBBBB

**Comment by monolithh** [comment]
@mairadanielaferrari i push fix for this. make sure that you have latest version of this code. 

i added fix in to `create_user.py`. can you try again and tell me problem fix for you?

**Comment by mairadanielaferrari** [comment]
looks good now. Thanks,

**Comment by mairadanielaferrari** [comment]
looks good now. Thanks,
