### ISSUE TITLE
Create Infrastructure Output Improvement

### ISSUE THREAD

**Issue by mairadanielaferrari** [monolithh/aws_fargate_boto3#4]
Can you please change the "create infrastructure" script output to print the name of the resources that were created as well ? When the create infrastructure script fails for some reason, I do not know which resources where created to go and delete them manually.
Thanks,

**Comment by monolithh** [comment]
@mairadanielaferrari done. please get newest code

**Comment by mairadanielaferrari** [comment]
Completed. Thanks,
